In [49]:
# Impoting libraries 
import pandas as pd
import numpy as np
import os

In [50]:
path = r'C:\Users\mauri\OneDrive\Documentos\Instacart Basket Analysis\02 Data'

In [51]:
df_merged = pd.read_pickle(os.path.join(path, 'Prepared data', 'merged_data_update.pkl'))

In [52]:
# Step 2
df_merged.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

In [53]:
# Step 3

##### In the subset we just got informaion from the departments: 4, 7, 13, 14, 16, 17, 19 and 20 and the data in the subset varies from the whole dataframe because in the subset we are not taking in consideration all the entries and just taking a sample for testing

In [54]:
# Step 4
#loyalty flag created in the excersise 4.8 notebook already

In [55]:
df_merged.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,new_customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77,7,9.0,both,Regularly busy,Average orders,10,New customer
1,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Least busy,Average orders,10,New customer
2,473747,1,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Least busy,Average orders,10,New customer
3,2254736,1,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Least busy,Average orders,10,New customer
4,431534,1,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Least busy,Average orders,10,New customer

In [56]:
# Step 5
df_merged.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

In [57]:
# Step 6
df_merged['average_price'] = df_merged.groupby(['user_id'])['prices'].transform(np.mean)

In [58]:
df_merged.loc[df_merged['average_price'] >= 10 , 'spending_flag'] = 'High spender'

In [59]:
df_merged.loc[df_merged['average_price'] < 10, 'spending_flag'] = 'Low spender'

In [60]:
df_merged['spending_flag'].value_counts()

Low spender     31770614
High spender      634245
Name: spending_flag, dtype: int64

In [61]:
# Step 7
df_merged['order_frequency'] = df_merged.groupby(['user_id'])['days_since_last_order'].transform(np.median)

In [62]:
df_merged.head(60)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,new_customer,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_price,spending_flag,order_frequency
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,...,7,9.0,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,...,7,9.0,both,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,False,196.0,1.0,1.0,...,7,9.0,both,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,False,196.0,1.0,1.0,...,7,9.0,both,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,False,196.0,1.0,1.0,...,7,9.0,both,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5
5,3367565,1,6,2,7,19.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
6,550135,1,7,1,9,20.0,False,196.0,1.0,1.0,...,7,9.0,both,Busiest days,Average orders,10,New customer,6.367797,Low spender,20.5
7,3108588,1,8,1,14,14.0,False,196.0,2.0,1.0,...,7,9.0,both,Busiest days,Average orders,10,New customer,6.367797,Low spender,20.5
8,2295261,1,9,1,16,0.0,False,196.0,4.0,1.0,...,7,9.0,both,Busiest days,Average orders,10,New customer,6.367797,Low spender,20.5
9,2550362,1,10,4,8,30.0,False,196.0,1.0,1.0,...,7,9.0,both,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5
10,2968173,15,15,1,9,7.0,False,196.0,2.0,0.0,...,7,9.0,both,Busiest days,Average orders,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,17,2,16,8.0,False,196.0,6.0,1.0,...,7,9.0,both,Regularly busy,Average orders,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,18,2,11,7.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,21,1,9,7.0,False,196.0,1.0,1.0,...,7,9.0,both,Busiest days,Average orders,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,22,1,10,14.0,False,196.0,1.0,1.0,...,7,9.0,both,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,2,5,14,6.0,False,196.0,3.0,0.0,...,7,9.0,both,Regularly busy,Average orders,9,New customer,8.372059,Low spender,6.0
16,1973799,19,5,6,12,8.0,False,196.0,15.0,1.0,...,7,9.0,both,Regularly busy,Average orders,9,New customer,8.372059,Low spender,6.0
17,532817,19,7,4,17,6.0,False,196.0,1.0,1.0,...,7,9.0,both,Least busy,Average orders,9,New customer,8.372059,Low spender,6.0
18,1573906,21,10,3,10,6.0,False,196.0,2.0,0.0,...,7,9.0,both,Least busy,Most orders,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,10,3,8,7.0,False,196.0,17.0,0.0,...,7,9.0,both,Least busy,Average orders,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,17,3,11,8.0,False,196.0,14.0,1.0,...,7,9.0,both,Least busy,Most orders,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,6,4,16,4.0,False,196.0,9.0,0.0,...,7,9.0,both,Least busy,Average orders,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,9,4,12,3.0,False,196.0,1.0,1.0,...,7,9.0,both,Least busy,Average orders,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,1,1,9,NaN,True,196.0,4.0,0.0,...,7,9.0,both,Busiest days,Average orders,27,Regular customer,6.356287,Low spender,8.0
24,1318871,52,2,1,10,7.0,False,196.0,5.0,1.0,...,7,9.0,both,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
25,1261384,52,3,1,10,7.0,False,196.0,3.0,1.0,...,7,9.0,both,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
26,580568,52,5,2,10,8.0,False,196.0,6.0,1.0,...,7,9.0,both,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
27,2428073,52,7,2,7,8.0,False,196.0,5.0,1.0,...,7,9.0,both,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
28,342306,52,9,1,11,7.0,False,196.0,5.0,1.0,...,7,9.0,both,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
29,1520353,52,10,2,10,8.0,False,196.0,4.0,1.0,...,7,9.0,both,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
30,2542086,52,11,2,9,7.0,False,196.0,3.0,1.0,...,7,9.0,both,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
31,944694,52,12,1,16,6.0,False,196.0,7.0,1.0,...,7,9.0,both,Busiest days,Average orders,27,Regular customer,6.356287,Low spender,8.0
32,1268191,52,15,2,11,8.0,False,196.0,3.0,1.0,...,7,9.0,both,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
33,1122089,52,17,2,10,6.0,False,196.0,4.0,1.0,...,7,9.0,both,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
34,1498922,52,18,2,10,14.0,False,196.0,6.0,1.0,...,7,9.0,both,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
35,180919,52,19,3,8,8.0,False,196.0,4.0,1.0,...,7,9.0,both,Least busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
36,2695875,52,21,5,10,30.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
37,3205960,67,1,3,11,NaN,True,196.0,1.0,0.0,...,7,9.0,both,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,2,1,15,5.0,False,196.0,2.0,1.0,...,7,9.0,both,Busiest days,Average orders,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,3,1,13,7.0,False,196.0,2.0,1.0,...,7,9.0,both,Busiest days,Average orders,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,4,2,9,8.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Average orders,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,5,3,14,8.0,False,196.0,2.0,1.0,...,7,9.0,both,Least busy,Average orders,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,6,3,12,7.0,False,196.0,2.0,1.0,...,7,9.0,both,Least busy,Average orders,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,8,2,11,7.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,9,2,14,7.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Average orders,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,10,1,10,6.0,False,196.0,1.0,1.0,...,7,9.0,both,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,11,1,11,7.0,False,196.0,1.0,1.0,...,7,9.0,both,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,12,2,12,8.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Average orders,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,13,1,10,6.0,False,196.0,1.0,1.0,...,7,9.0,both,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,14,1,9,7.0,False,196.0,1.0,1.0,...,7,9.0,both,Busiest days,Average orders,24,Regular customer,7.656790,Low spender,7.0
50,768572,67,16,4,10,9.0,False,196.0,1.0,1.0,...,7,9.0,both,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
51,150528,67,18,5,16,4.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Average orders,24,Regular customer,7.656790,Low spender,7.0
52,29758,67,19,0,14,9.0,False,196.0,2.0,1.0,...,7,9.0,both,Busiest days,Average orders,24,Regular customer,7.656790,Low spender,7.0
53,1558976,67,21,1,9,5.0,False,196.0,2.0,1.0,...,7,9.0,both,Busiest days,Average orders,24,Regular customer,7.656790,Low spender,7.0
54,863974,67,22,1,11,14.0,False,196.0,3.0,1.0,...,7,9.0,both,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
55,2308399,67,23,1,14,14.0,False,196.0,1.0,1.0,...,7,9.0,both,Busiest days,Average orders,24,Regular customer,7.656790,Low spender,7.0
56,2759128,81,3,1,9,14.0,False,196.0,2.0,0.0,...,7,9.0,both,Busiest days,Average orders,7,New customer,8.165385,Low spender,30.0
57,1812985,81,5,2,20,30.0,False,196.0,1.0,1.0,...,7,9.0,both,Regularly busy,Average orders,7,New customer,8.165385,Low spender,30.0
58,1889835,82,1,3,15,NaN,True,196.0,6.0,0.0,...,7,9.0,both,Least busy,Average orders,19,Regular customer,6.441221,Low spender,11.5
59,499460,82,3,5,10,5.0,False,196.0,2.0,1.0,...,7,9.0,both,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5

In [80]:
df_merged.loc[df_merged['order_frequency'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [81]:
df_merged.loc[(df_merged['order_frequency'] > 10) & (df_merged['order_frequency'] <= 20), 'order_frequency_flag'] = 'Regular customer'

In [82]:
df_merged.loc[df_merged['order_frequency'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [83]:
df_merged['order_frequency_flag'].value_counts()

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
Name: order_frequency_flag, dtype: int64

In [84]:
df_merged.to_pickle(os.path.join(path, 'Prepared data', 'merged_data_good.pkl'))